FROM public.ecr.aws/aws-cli/aws-cli:2.9.19

LABEL author="Alexis Lucattini" \
      description="Run aws cli" \
      maintainer="alexis.lucattini@umccr.org"

RUN yum install -y -q \
        tar \
        gzip

ENTRYPOINT [ ]
CMD [ "aws" ]
