name: build_docker_container_and_push_to_ghcrio

on:
  push:
    branches:
      - "main"

concurrency: image_builds

jobs:
  get_images_to_build:
    runs-on: ubuntu-latest
    steps:
      # Standard checkout step
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      # Log in to GitHub Container registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Determine images that need work
      - id: get_images_to_build
        run: |
          python3 .github/scripts/get-images-to-build.py
        env:
          REPO_NAME: ${{ github.repository_owner }}
    # Output value for images to build
    outputs:
      image_tags_to_build: ${{ steps.get_images_to_build.outputs.image_tags_to_build }}
  scatter_image_builds:
    needs: get_images_to_build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_tag: ${{ fromJSON(needs.get_images_to_build.outputs.image_tags_to_build) }}
      fail-fast: false  # Don't fail if one image fails to run
    steps:
      # Standard checkout step
      - name: Checkout code
        id: git_checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      # Tag to path
      - name: Strip tag as path
        id: tag_to_path
        run: echo "::set-output name=image_path::$( echo ${{ matrix.image_tag }} | tr ':' '/' )"
      # Use qemu to perform multiplatform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # Use docker buildx to build multi-platform containers
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          use: true
          install: true
          config-inline: |
            [worker.oci]
              max-parallelism = 2
      # Log in to GitHub Container registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Build and push docker images
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: repositories/${{ steps.tag_to_path.outputs.image_path }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image_tag }}
      # Ensure if image is latest, push latest tag with skopeo
      # Determine images that need work
      - name: Push latest tag
        id: push_latest_tag
        shell: bash
        run: |
          # Push latest tag
          # Install packaging 
          pip3 install --quiet packaging
          # Run latest tag python script
          python3 .github/scripts/push-latest-tag.py
        env:
          REGISTRY: ghcr.io
          ORG_NAME: ${{ github.repository_owner }}
          REPO_TAG: ${{ matrix.image_tag }}
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}